### ISSUE TITLE
Search for possible external APIs that can provide needed Route Data

### ISSUE THREAD

**Issue by finnge** [neuro-inclusive-transit/development#18]
### AKs

- [x] Routen API(s) gefunden, die Anforderungen aus User Stories entspricht
- [x] API für Karten-Ansicht gefunden
- [ ] Vor- und Nachteile der Anbieter in einem ADR dokumentiert

**Comment by leo-3108** [comment]
Research-Ergebnisse sind im FigJam dokumentiert: https://www.figma.com/file/YXBqSf42uMzAjgqV4KJmEO/P2-%E2%80%93-Projekt-Board?node-id=41-74&t=dMiYNLLSbSeGMglq-4
