### ISSUE TITLE
provide DisturbanceAPI and async publishing of data

### ISSUE THREAD

**Issue by finnge** [neuro-inclusive-transit/development#8]
Aktueller Plan:

- Disturbance-API nimmt Schlüsselhaltestellen bei Bahn Verbindungen und checkt über die TimeTables-API der DB, ob die Zugverbindungen pünktlich sind.
- Bei Verspätungen wird das Endgerät asynchron über diese informiert
- Bei Start eine (bereits früher definierten Route) wird einmal die aktuelle Pünktlichkeit aller Zugverbindungen gecheckt

**Comment by leo-3108** [comment]
> Mögliches Problem:
> 
> * Die TimeTables-API der DB benötigt eine ID des entsprechenden Bahnhofs/Haltestelle. Hierfür muss unter Umständen zuerst eine andere API angefragt werden, um diese ID zu erfahren [Ability to get and store disturbance data from external sources #7](https://github.com/neuro-inclusive-transit/development/issues/7)

Über die [DB-StationData-API](https://developers.deutschebahn.com/db-api-marketplace/apis/product/stada/api/51622#/StaDaStationData_272/operation/%2Fstations/get) können alle Haltestellen ausgegeben oder nach einer Haltestelle gesucht werden. Als Response liefert die API unter anderem die ID der Haltestelle.
